name: Telemetry Monitoring Agents

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
      agent:
        description: "Agent to run (blank = all)"
        required: false
        type: string

permissions:
  contents: write

jobs:
  run-agents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace (includes agent state)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install BC Telemetry Buddy MCP
        run: npm install -g bc-telemetry-buddy-mcp

      - name: Run agent(s)
        run: |
          if [ -n "${{ inputs.agent }}" ]; then
            bctb-mcp agent run "${{ inputs.agent }}" --once
          else
            bctb-mcp agent run-all --once
          fi
        env:
          BCTB_AUTH_FLOW: client_credentials
          BCTB_TENANT_ID: ${{ secrets.BCTB_TENANT_ID }}
          BCTB_CLIENT_ID: ${{ secrets.BCTB_CLIENT_ID }}
          BCTB_CLIENT_SECRET: ${{ secrets.BCTB_CLIENT_SECRET }}
          BCTB_APP_INSIGHTS_ID: ${{ secrets.BCTB_APP_INSIGHTS_ID }}
          BCTB_KUSTO_CLUSTER_URL: ${{ secrets.BCTB_KUSTO_CLUSTER_URL }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
          AZURE_OPENAI_DEPLOYMENT: gpt-4o
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          GRAPH_CLIENT_SECRET: ${{ secrets.GRAPH_CLIENT_SECRET }}
          DEVOPS_PAT: ${{ secrets.DEVOPS_PAT }}

      - name: Commit updated agent state
        run: |
          git config user.name "bctb-agent"
          git config user.email "bctb-agent@noreply.github.com"
          git add agents/
          if git diff --cached --quiet; then
            echo "No state changes"
          else
            git commit -m "agent: run $(date -u +%Y-%m-%dT%H:%M)Z"
            git push
          fi
